CREATE TABLE PERSONAL(
  ID_PERSONAL NUMERIC(6,0) NOT NULL PRIMARY KEY,
  ID_MEDICO NUMERIC(6,0) NULL,
  NOMBRES VARCHAR2(100) NOT NULL,
  APELLIDOS VARCHAR(60) NULL,
  TIPO_DOC CHAR(1) NOT NULL,
  NUM_DOC VARCHAR2(20) NOT NULL,
  NUM_CELULAR VARCHAR2(9) NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  DIRECCION VARCHAR2(120) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1' NOT NULL
);


CREATE SEQUENCE SEQ_PERSONAL;

INSERT INTO PERSONAL(ID_PERSONAL,ID_MEDICO,NOMBRES,APELLIDOS,TIPO_DOC,NUM_DOC,NUM_CELULAR,EMAIL,DIRECCION)
VALUES (SEQ_PERSONAL.NEXTVAL,'1','Pedro Antonio','Murillo Ulloa','1','44986300','985266877','pedro.murillo@gmail.com','Av. Los Incas Nro. 152');

INSERT INTO PERSONAL(ID_PERSONAL,ID_MEDICO,NOMBRES,APELLIDOS,TIPO_DOC,NUM_DOC,NUM_CELULAR,EMAIL,DIRECCION)
VALUES (SEQ_PERSONAL.NEXTVAL,'2','Maria Cristhina','Horna Dulanto','1','40409845','98652147','mari.horna@gmail.com','Jr. Mujica Nro. 286');

COMMIT;