CREATE TABLE PROGRAMACION
(
    ID_PROGRAMACION integer NOT NULL,
    ID_ESPECIALIDAD integer NOT NULL,
    ID_MEDICO integer NOT NULL,
    FECHA date NOT NULL,
    CUPOS_PROG integer NOT NULL,
    CUPOS_DISP integer,
    ESTADO character varying(1),
    PRIMARY KEY (ID_PROGRAMACION)
);

CREATE SEQUENCE SEQ_PROGRAMACION
    START 1
    INCREMENT 1;
	
INSERT INTO PROGRAMACION(ID_PROGRAMACION,ID_ESPECIALIDAD,ID_MEDICO,FECHA,CUPOS_PROG,CUPOS_DISP,ESTADO)
VALUES (NEXTVAL('SEQ_PROGRAMACION'), '1','1','15/11/2021','10','10','1');	

INSERT INTO PROGRAMACION(ID_PROGRAMACION,ID_ESPECIALIDAD,ID_MEDICO,FECHA,CUPOS_PROG,CUPOS_DISP,ESTADO)
VALUES (NEXTVAL('SEQ_PROGRAMACION'), '2','2','16/11/2021','12','12','1');

INSERT INTO PROGRAMACION(ID_PROGRAMACION,ID_ESPECIALIDAD,ID_MEDICO,FECHA,CUPOS_PROG,CUPOS_DISP,ESTADO)
VALUES (NEXTVAL('SEQ_PROGRAMACION'), '2','2','18/11/2021','12','12','1');