CREATE TABLE PERSONAL
(
    ID_PERSONAL integer NOT NULL,
    ID_MEDICO integer NOT NULL,
    NOMBRES VARCHAR(100) NULL,
    APELLIDOS VARCHAR(60) NULL,
    FEC_INGRESO date NOT NULL,
    ESTADO VARCHAR(1) NULL DEFAULT '1',
    PRIMARY KEY (ID_PERSONAL)
);

CREATE SEQUENCE SEQ_PERSONAL
    START 1
    INCREMENT 1;

INSERT INTO PERSONAL(ID_PERSONAL,ID_MEDICO,NOMBRES,APELLIDOS,FEC_INGRESO,ESTADO)
VALUES (NEXTVAL('SEQ_PERSONAL'),'1','Pedro Antonio','Murillo Ulloa','10/02/2015','1');

INSERT INTO PERSONAL(ID_PERSONAL,ID_MEDICO,NOMBRES,APELLIDOS,FEC_INGRESO,ESTADO)
VALUES (NEXTVAL('SEQ_PERSONAL'),'2','Maria Cristhina','Horna Dulanto','13/06/2018','1');