CREATE TABLE PACIENTE(
  ID_PACIENTE NUMERIC(6,0) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(100) NOT NULL,
  APE_PATERNO VARCHAR2(60) NOT NULL,
  APE_MATERNO VARCHAR2(60) NOT NULL,
  TIPO_DOC CHAR(1) NOT NULL,
  NUM_DOC VARCHAR2(20) NOT NULL,
  FEC_NACIMIENTO DATE,
  NUM_CELULAR VARCHAR2(9) NOT NULL,
  EMAIL VARCHAR2(50) NOT NULL,
  DIRECCION VARCHAR2(120) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1' NOT NULL
);

ALTER SESSION SET nls_date_format='dd/mm/yyyy';

CREATE SEQUENCE SEQ_PACIENTE;

INSERT INTO PACIENTE(ID_PACIENTE,NOMBRE,APE_PATERNO,APE_MATERNO,TIPO_DOC,NUM_DOC,FEC_NACIMIENTO,NUM_CELULAR,EMAIL,DIRECCION)
VALUES (SEQ_PACIENTE.NEXTVAL,'José Luis','Abreu','Hernández','1','44914357','03/03/1985','985478524','jose.abreu@gmail.com','Av. Los Pinos Nro. 168');

INSERT INTO PACIENTE(ID_PACIENTE,NOMBRE,APE_PATERNO,APE_MATERNO,TIPO_DOC,NUM_DOC,FEC_NACIMIENTO,NUM_CELULAR,EMAIL,DIRECCION)
VALUES (SEQ_PACIENTE.NEXTVAL,'María Laura','Acosta','Torres','1','40401586','12/07/1990','96585274','mari.acosta@gmail.com','Jr. Augustin Gamarra Nro. 105');

COMMIT;

SELECT *FROM PACIENTE;