CREATE TABLE ESPECIALIDAD (
  `ID_ESPECIALIDAD` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE` VARCHAR(80) NULL COMMENT 'Nombre',
  `ESTADO` VARCHAR(1) NULL DEFAULT '1' COMMENT 'Estado del Registro'
);

INSERT INTO ESPECIALIDAD (NOMBRE, ESTADO) 
VALUES ('Medicina General','1');

INSERT INTO ESPECIALIDAD (NOMBRE, ESTADO) 
VALUES ('Cardiología','1');

INSERT INTO ESPECIALIDAD (NOMBRE, ESTADO) 
VALUES ('Pediatría','1');