application:
  title: Microservicios de Api Gateway
  version: 1.0.0
  author: R.PINEDA

server:
  port: 8887


# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
# Matricula de Microservicios
spring:
  cloud:
    gateway:
      discovery.locator:    #A           
          enabled: true           
          lowerCaseServiceId: true
      routes:
      - id: id-ms-gestion-pacientes
        uri: lb://MS-GESTION-PACIENTES
        predicates:
        - Path=/path-pacientes/**
        filters:
        - RewritePath=/path-pacientes/(?<path>.*), /$\{path}        
      - id: id-albums
        uri: https://jsonplaceholder.typicode.com/albums
        predicates:
        - Path=/albums

# Activacion de endpoints (Actuator)
management:
     endpoints:
       web:
         exposure:
           include: '*'
     endpoint:
       health:
         show-details: always