application:
  title: Microservicios de Medicos 
  version: 1.0.0
  author: R.PINEDA

server:
  port: 8082
#  servlet:
#    context-path: /ms-medicos
    
# MySQL #
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_medicos?serverTimezone=GMT-6
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka 