application:
  title: Microservicios de Programacion de Cupos
  version: 1.0.0
  author: R.PINEDA

server:
  port: 8084
#  servlet:
#    context-path: /ms-programacion-cupos
    
# Postgres #
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MS_PROGRAMACION
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    
# Registry Client
eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka    