server:
 port: 8888

spring:
  application:
    name: ms-admin-config-server
    
#Configuracion Local
#  profiles:
#    active: native
#  cloud:
#    config:
#      server: 
#        native:
#          searchLocations: file:///D:/JAVA MICROSERVICIOS - MATERIAL/Proyect/ms-admin-config-data
          

#Configuracion Cloud (git)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RPinedaE/MS-PROYECT-2021.git
          default-label: 02-Config-Server
          search-paths: ms-admin-config-data
          username: ${USER_NAME}
          password: ${USER_PASSWORD}
          clone-on-start: true
          force-pull: true
          timeout: 5