CREATE TABLE CITA_MEDICA (
  ID_CITA NUMERIC(6,0) NOT NULL PRIMARY KEY,
  ID_PACIENTE NUMERIC(6,0) NOT NULL,
  ID_ESPECIALIDAD NUMERIC(6,0) NOT NULL,
  ID_MEDICO NUMERIC(6,0) NOT NULL,
  FECHA DATE NOT NULL,
  HORA VARCHAR2(5),
  MOTIVO VARCHAR2(120),
  ESTADO CHAR(1) DEFAULT '1' NOT NULL,
  SITUACION CHAR(1)
);


ALTER SESSION SET nls_date_format = 'dd/mm/yyyy'

CREATE SEQUENCE SEQ_CITA_MEDICA;

INSERT INTO CITA_MEDICA(ID_CITA,ID_PACIENTE,ID_ESPECIALIDAD,ID_MEDICO,FECHA,HORA,MOTIVO)
VALUES (SEQ_CITA_MEDICA.NEXTVAL,1,1,1,'10/12/2021','','Paciente con comorbilidad');

INSERT INTO CITA_MEDICA(ID_CITA,ID_PACIENTE,ID_MEDICO,ID_ESPECIALIDAD,FECHA,HORA,MOTIVO)
VALUES (SEQ_CITA_MEDICA.NEXTVAL,2,2,2,'11/12/2021','','Paciente con riesgo quirúrgico');

INSERT INTO CITA_MEDICA(ID_CITA,ID_PACIENTE,ID_MEDICO,ID_ESPECIALIDAD,FECHA,HORA,MOTIVO)
VALUES (SEQ_CITA_MEDICA.NEXTVAL,2,3,1,'14/12/2021','','Paciente con riesgo quirúrgico');

COMMIT;
